name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        set +x
        pwd
        git submodule update --init --recursive
        cd ..
        mkdir build
        cd build
        cmake ../inviwo
        cmake --build .
      shell: bash
